### ISSUE TITLE
%server:online% off by 1 on player join / leave

### ISSUE THREAD

**Issue by SulpherStaer** [Reimnop/Discord4Fabric#15] opened 2022-06-14 21:45 UTC
When embedded in the player join or leave message the %server:online% is off by 1 because it sends the message before the player has fully joined, or just before they have fully left.

This likely is difficult to fix. I personally would like it if I could do a maths on the variable. by doing +1 or -1. that way it is accurate.

Or... if it is easy to fix, I'd obviously prefer that.

**Comment by Reimnop** [comment] 2022-06-15 03:35
Intended behavior, but I'll fix it by adding a `post_online` placeholder

**Comment by Reimnop** [comment] 2022-06-15 06:44
Fixed in [this commit](https://github.com/Reimnop/Discord4Fabric/commit/294f38dc06c5feec101463bf1d7c5b042e8aa026)

**Closed by Reimnop** 2022-06-15 06:44 UTC
Labels: bug

**Comment by SulpherStaer** [comment] 2022-06-15 06:46
gimme your PayPal or something. this was really fast and deserves rewarding.

**Comment by Reimnop** [comment] 2022-06-15 06:50
Thanks for the compliment. Unfortunately I feel it's unethical to receive money for an MIT licensed project.
